site_name: Home
site_author: Eduardo Furlan
site_description: My random personal notes
site_url: https://efurlanm.github.io/home/
copyright: CC BY 4.0 License
repo_name: home
repo_url: http://github.com/efurlanm/home/
site_dir: docs
docs_dir: src
use_directory_urls: false
theme:
    font: false                 # no external fonts
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: orange
        accent: orange
    features:
        - header.autohide
        - navigation.tracking   # address shows active anchor
plugins:
    - search
    - blog:
        post_readtime: false
extra_css:
    - assets/extra.css
    - assets/katex/katex.min.css
    #- https://unpkg.com/katex/dist/katex.min.css
extra_javascript:
    # squidfunk.github.io/mkdocs-material/reference/math/
    - assets/katex.js
    - assets/katex/katex.min.js
    - assets/katex/contrib/auto-render.min.js
    #- https://unpkg.com/katex/dist/katex.min.js
    #- https://unpkg.com/katex/dist/contrib/auto-render.min.js    
markdown_extensions:
    - tables
    - pymdownx.arithmatex:
        generic: true           # used with katex
not_in_nav: |
    assets/
exclude_docs: |
    .*
    *ยง*
