site_name: Language Design and Implementation
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/ldi/
copyright: CC BY 4.0 License
repo_name: LDI
repo_url: http://github.com/efurlanm/ldi/
docs_dir: src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: orange
        accent: orange
    font: false
    features:
        - header.autohide
plugins:
    - search
    - blog:
        post_readtime: false
    - macros
extra:
    repo: https://github.com/efurlanm/ldi/tree/main/src/
extra_css:
    - css/extra.css
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css
extra_javascript:
    - javascripts/katex.js
    - https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js
    - https://cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
markdown_extensions:
    - def_list
    - md_in_html
    - tables
    - pymdownx.snippets:
        check_paths: true
        base_path: src/include
exclude_docs: |
    .*
